---

- name: List artisan commands
  shell: chdir={{ ansistrano_release_path.stdout }}
    {{ php_path }} artisan
  register: artisan_commands

- name: Optimize code
  shell: chdir={{ ansistrano_release_path.stdout }}
    {{ php_path }} artisan clear-compiled && {{ php_path }} artisan optimize
  when: artisan_commands.stdout.find('optimize') != -1
